
import { useState } from "react";
import { motion } from "framer-motion";
import { Card } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { 
  Ship, 
  PipeLine, 
  Train, 
  Building, 
  Droplet, 
  ArrowRight, 
  Banknote,
  Factory
} from "lucide-react";

const methodData = [
  {
    id: "production",
    title: "Oil Production",
    icon: <Droplet className="h-6 w-6 text-amber-300" />,
    description: "Companies organized like mining operations with workers' camps and teams of engineers operated the new rotary drilling equipment that replaced the older percussion drills.",
    details: [
      "Royal Dutch dominated production in the Dutch East Indies (Indonesia)",
      "Burmah Oil controlled oil fields in Burma (Myanmar)",
      "Nobel Brothers developed the Baku oil fields in Russia (Azerbaijan)",
      "New rotary drilling technology replaced percussion drills",
      "Workers' camps and engineering teams established at production sites"
    ],
    color: "bg-amber-700/20",
    image: "https://images.unsplash.com/photo-1518544801976-5e38c3864d9e?q=80&w=2670&auto=format&fit=crop"
  },
  {
    id: "transport",
    title: "Transportation Networks",
    icon: <PipeLine className="h-6 w-6 text-blue-300" />,
    description: "Control of transportation routes became a key method of dominating the oil industry, with companies developing pipelines, railways, and tanker ships.",
    details: [
      "Shell Transport Company pioneered ocean-going tankers",
      "Standard Oil built extensive pipeline networks",
      "Railway shipping controlled by major companies",
      "Transportation monopolies created barriers to entry",
      "Control of shipping routes allowed price manipulation"
    ],
    color: "bg-blue-700/20",
    image: "https://images.unsplash.com/photo-1544965850-6f8a66788b99?q=80&w=2787&auto=format&fit=crop"
  },
  {
    id: "refining",
    title: "Refining Operations",
    icon: <Factory className="h-6 w-6 text-red-300" />,
    description: "Companies like Standard Oil built their empires by first monopolizing the refining industry with faster techniques using steam power generated by fuel oil.",
    details: [
      "Standard Oil began domination through refining monopoly",
      "Technological innovations increased refining speed and efficiency",
      "Steam power generated by fuel oil revolutionized the process",
      "Economies of scale drove smaller refineries out of business",
      "Control of refining created leverage over both producers and distributors"
    ],
    color: "bg-red-700/20",
    image: "https://images.unsplash.com/photo-1518709414768-a88981a4515d?q=80&w=2273&auto=format&fit=crop"
  },
  {
    id: "distribution",
    title: "Global Distribution",
    icon: <Building className="h-6 w-6 text-green-300" />,
    description: "Major companies established worldwide distribution networks with storage tanks, delivery systems, and reusable containers, replacing independent importers and wholesalers.",
    details: [
      "Networks of storage tanks established worldwide",
      "Horse-drawn delivery wagons created last-mile distribution",
      "Reusable tin cans standardized oil sales",
      "Replacement of independent importers and wholesalers",
      "Standard Oil's global distribution network created vertical integration"
    ],
    color: "bg-green-700/20",
    image: "https://images.unsplash.com/photo-1570358934836-6802981e481e?q=80&w=2787&auto=format&fit=crop"
  },
  {
    id: "finance",
    title: "Financial Control",
    icon: <Banknote className="h-6 w-6 text-yellow-300" />,
    description: "Banking houses and investment firms gained control of the oil industry by financing infrastructure and operations, creating another layer of control.",
    details: [
      "Banking houses financed pipelines and railways",
      "Investment capital provided control without direct ownership",
      "Financial institutions influenced industry development",
      "Mellon family in Pittsburgh financed oil operations",
      "Deutsche Bank invested in Middle Eastern oil infrastructure"
    ],
    color: "bg-yellow-700/20",
    image: "https://images.unsplash.com/photo-1607944024060-0450380ddd33?q=80&w=2787&auto=format&fit=crop"
  }
];

const TransportationMethods = () => {
  const [activeMethod, setActiveMethod] = useState("production");

  return (
    <div className="space-y-6">
      <motion.div
        className="bg-slate-800/50 rounded-lg p-6 md:p-8 border border-amber-900/30"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <h2 className="text-2xl md:text-3xl font-bold mb-6 text-amber-400 flex items-center">
          <PipeLine className="mr-3 h-7 w-7" /> Control Methods
        </h2>
        <p className="text-slate-200 mb-8 max-w-4xl">
          Oil empires used various methods to control the global supply chain, from production to distribution.
          Each company specialized in different aspects of the industry to establish dominance.
        </p>
        
        <div className="grid md:grid-cols-5 gap-2 mb-8">
          {methodData.map((method) => (
            <motion.div
              key={method.id}
              className={`${
                activeMethod === method.id 
                  ? `${method.color} border-opacity-50` 
                  : 'bg-slate-700/30 hover:bg-slate-700/50'
              } rounded-lg border border-slate-600/30 p-3 cursor-pointer transition-all duration-200`}
              whileHover={{ scale: activeMethod === method.id ? 1 : 1.03 }}
              onClick={() => setActiveMethod(method.id)}
            >
              <div className="flex flex-col items-center text-center">
                <div className={`${
                  activeMethod === method.id 
                    ? 'opacity-100 scale-110' 
                    : 'opacity-70'
                  } transition-all duration-200`}>
                  {method.icon}
                </div>
                <h3 className={`mt-2 font-medium ${
                  activeMethod === method.id 
                    ? 'text-white' 
                    : 'text-slate-300'
                }`}>
                  {method.title}
                </h3>
              </div>
            </motion.div>
          ))}
        </div>
        
        <div className="mt-6">
          {methodData.map((method) => (
            <motion.div
              key={method.id}
              className={`${activeMethod === method.id ? 'block' : 'hidden'}`}
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.5 }}
            >
              <div className="grid md:grid-cols-5 gap-8">
                <div className="md:col-span-2">
                  <div 
                    className="w-full h-64 md:h-full rounded-lg bg-cover bg-center mb-4"
                    style={{ 
                      backgroundImage: `url(${method.image})`,
                      boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.3)'
                    }}
                  ></div>
                </div>
                
                <div className="md:col-span-3 space-y-4">
                  <div className="flex items-center">
                    <div className={`p-2 rounded-full ${method.color} mr-3`}>
                      {method.icon}
                    </div>
                    <h3 className="text-xl md:text-2xl font-bold text-slate-100">{method.title}</h3>
                  </div>
                  
                  <p className="text-slate-300 text-lg leading-relaxed">
                    {method.description}
                  </p>
                  
                  <div className="bg-slate-700/30 rounded-lg border border-slate-600/30 p-4">
                    <h4 className="text-amber-300 font-medium mb-3">Key Aspects</h4>
                    <ul className="space-y-2">
                      {method.details.map((detail, index) => (
                        <motion.li 
                          key={index}
                          className="flex items-start text-slate-200"
                          initial={{ opacity: 0, x: -10 }}
                          animate={{ opacity: 1, x: 0 }}
                          transition={{ delay: index * 0.1, duration: 0.3 }}
                        >
                          <ArrowRight className="h-5 w-5 mr-2 text-amber-400 flex-shrink-0 mt-0.5" />
                          <span>{detail}</span>
                        </motion.li>
                      ))}
                    </ul>
                  </div>
                  
                  <div className="bg-slate-700/30 rounded-lg border border-slate-600/30 p-4">
                    <h4 className="text-amber-300 font-medium mb-2">Historical Impact</h4>
                    <p className="text-slate-200">
                      {method.id === "production" && "Control of oil fields created the foundation for vertical integration and market dominance. Companies that controlled production had leverage over the entire supply chain."}
                      {method.id === "transport" && "Transportation networks created natural monopolies. Companies that controlled shipping routes could control prices and exclude competitors."}
                      {method.id === "refining" && "Refining innovations allowed companies like Standard Oil to create economies of scale that drove smaller competitors out of business."}
                      {method.id === "distribution" && "Global distribution networks eliminated middlemen and allowed oil companies to control the entire value chain from well to consumer."}
                      {method.id === "finance" && "Financial control created a new dimension of power in the oil industry, allowing banks and investors to influence strategic decisions."}
                    </p>
                  </div>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </motion.div>
    </div>
  );
};

export default TransportationMethods;
