// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjuichupgupuffzkwktr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqdWljaHVwZ3VwdWZmemt3a3RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNzM4NjAsImV4cCI6MjA1OTc0OTg2MH0.IPg0-kN_K5UKvL4DbuEaEiXUxIGNyQJ5Xhw7YPKyQYc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);